ALTER TABLE REVIEW DROP CONSTRAINT review_users_fk;
ALTER TABLE REVIEW DROP CONSTRAINT review_product_fk;
ALTER TABLE REVIEW ADD CONSTRAINT review_users_fk FOREIGN KEY(user_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE REVIEW ADD CONSTRAINT review_product_fk FOREIGN KEY(post_id) REFERENCES Post(post_id) ON DELETE CASCADE;

ALTER TABLE POST DROP CONSTRAINT post_users_fk;
ALTER TABLE POST DROP CONSTRAINT post_product_fk;
ALTER TABLE POST ADD CONSTRAINT post_users_fk FOREIGN KEY(poster_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE POST ADD CONSTRAINT post_product_fk FOREIGN KEY(product_id) REFERENCES Product(product_id) ON DELETE CASCADE;

ALTER TABLE CMNT DROP CONSTRAINT cmnt_users_fk;
ALTER TABLE CMNT DROP CONSTRAINT cmnt_post_fk;
ALTER TABLE CMNT ADD CONSTRAINT cmnt_users_fk FOREIGN KEY(writer_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE CMNT ADD CONSTRAINT cmnt_post_fk FOREIGN KEY(post_id) REFERENCES Post(post_id) ON DELETE CASCADE;

ALTER TABLE POSTUPVOTE DROP CONSTRAINT postupvote_users_fk;
ALTER TABLE POSTUPVOTE DROP CONSTRAINT postupvote_post_fk;
ALTER TABLE POSTUPVOTE ADD CONSTRAINT postupvote_users_fk FOREIGN KEY(user_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE POSTUPVOTE ADD CONSTRAINT postupvote_post_fk FOREIGN KEY(post_id) REFERENCES Post(post_id) ON DELETE CASCADE;

ALTER TABLE CMNTUPVOTE DROP CONSTRAINT cmntupvote_users_fk;
ALTER TABLE CMNTUPVOTE DROP CONSTRAINT cmntupvote_cmnt_fk;
ALTER TABLE CMNTUPVOTE ADD CONSTRAINT cmntupvote_users_fk FOREIGN KEY(user_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE CMNTUPVOTE ADD CONSTRAINT cmntupvote_cmnt_fk FOREIGN KEY(cmnt_id) REFERENCES Cmnt(cmnt_id) ON DELETE CASCADE;

ALTER TABLE REVIEWUPVOTE DROP CONSTRAINT reviewupvote_users_fk;
ALTER TABLE REVIEWUPVOTE DROP CONSTRAINT reviewupvote_review_fk;
ALTER TABLE REVIEWUPVOTE ADD CONSTRAINT reviewupvote_users_fk FOREIGN KEY(user_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE REVIEWUPVOTE ADD CONSTRAINT reviewupvote_review_fk FOREIGN KEY(review_id) REFERENCES Review(review_id) ON DELETE CASCADE;

ALTER TABLE PRODUCTIMAGE DROP CONSTRAINT productimage_product_fk;
ALTER TABLE PRODUCTIMAGE ADD CONSTRAINT productimage_product_fk FOREIGN KEY(product_id) REFERENCES Product(product_id) ON DELETE CASCADE;

ALTER TABLE POSTIMAGE DROP CONSTRAINT postimage_post_fk;
ALTER TABLE POSTIMAGE ADD CONSTRAINT postimage_post_fk FOREIGN KEY(post_id) REFERENCES Post(post_id) ON DELETE CASCADE;

ALTER TABLE BELONGSTO DROP CONSTRAINT belongsto_product_fk;
ALTER TABLE BELONGSTO DROP CONSTRAINT belongsto_tag_fk;
ALTER TABLE BELONGSTO ADD CONSTRAINT belongsto_product_fk FOREIGN KEY(product_id) REFERENCES Product(product_id) ON DELETE CASCADE;
ALTER TABLE BELONGSTO ADD CONSTRAINT belongsto_tag_fk FOREIGN KEY(tag_id) REFERENCES Tag(tag_id) ON DELETE CASCADE;

ALTER TABLE WISHLIST DROP CONSTRAINT wishlist_user_fk;
ALTER TABLE WISHLIST DROP CONSTRAINT wishlist_product_fk;
ALTER TABLE WISHLIST ADD CONSTRAINT wishlist_user_fk FOREIGN KEY(user_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE WISHLIST ADD CONSTRAINT wishlist_product_fk FOREIGN KEY(product_id) REFERENCES Product(product_id) ON DELETE CASCADE;

ALTER TABLE CART DROP CONSTRAINT cart_user_fk;
ALTER TABLE CART DROP CONSTRAINT cart_post_fk;
ALTER TABLE CART ADD CONSTRAINT cart_user_fk FOREIGN KEY(user_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE CART ADD CONSTRAINT cart_post_fk FOREIGN KEY(post_id) REFERENCES Post(post_id) ON DELETE CASCADE;

ALTER TABLE TRANSACTION DROP CONSTRAINT transaction_user_fk;
ALTER TABLE TRANSACTION DROP CONSTRAINT transaction_post_fk;
ALTER TABLE TRANSACTION ADD CONSTRAINT transaction_user_fk FOREIGN KEY(user_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE TRANSACTION ADD CONSTRAINT transaction_post_fk FOREIGN KEY(post_id) REFERENCES Post(post_id) ON DELETE CASCADE;

ALTER TABLE FOLLOW DROP CONSTRAINT follow_user_fk;
ALTER TABLE FOLLOW DROP CONSTRAINT follow_tag_fk;
ALTER TABLE FOLLOW ADD CONSTRAINT follow_user_fk FOREIGN KEY(user_id) REFERENCES Users(user_id) ON DELETE CASCADE;
ALTER TABLE FOLLOW ADD CONSTRAINT follow_tag_fk FOREIGN KEY(tag_id) REFERENCES Tag(tag_id) ON DELETE CASCADE;