SELECT C.POST_ID AS POST_ID, P.DESCRIPTION AS DESCRIPTION, U.NAME AS USERNAME, PR.NAME AS PRODUCTNAME, C.QUANTITY AS QUANTITY, P.NEGOTIABLE AS NEGOTIABLE, C.TOTAL AS TOTAL, GET_FIRST_POST_IMAGE(C.POST_ID) AS IMG
FROM CART C 
JOIN POST P ON C.POST_ID = P.POST_ID
JOIN USERS U ON U.USER_ID = P.POSTER_ID
JOIN PRODUCT PR ON PR.PRODUCT_ID = P.PRODUCT_ID
WHERE C.USER_ID = 10;