CREATE OR REPLACE TRIGGER CART_QUANTITY_UPDATE
BEFORE UPDATE
OF QUANTITY
ON CART
FOR EACH ROW
DECLARE
	NEW_TOTAL NUMBER;
	REMAINING NUMBER;
BEGIN
	SELECT :NEW.QUANTITY * PRICE INTO NEW_TOTAL
	FROM POST
	WHERE POST_ID = :OLD.POST_ID;
	
	SELECT REM_QUANTITY INTO REMAINING
	FROM POST
	WHERE POST_ID = :OLD.POST_ID;
	
	IF :NEW.QUANTITY > REMAINING THEN
		:NEW.QUANTITY := :OLD.QUANTITY;
	ELSE
		:NEW.TOTAL := NEW_TOTAL;
	END IF;
END;
/

CREATE OR REPLACE TRIGGER PUT_DEFAULT_DP
BEFORE INSERT OR UPDATE
ON USERS
FOR EACH ROW
BEGIN
	IF :NEW.DP IS NULL THEN
		:NEW.DP := 'images/dp_placeholder.png';
	END IF;
END;
/